'use client'
import { AuthContextProvider } from './context/AuthContext'
import Nav from './components/navigation/Nav'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Ath App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <AuthContextProvider>
          <header>
            <Nav />
          </header>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}
